name: Translate README

on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - name: Auto Translate
        uses: BaiJiangJie/translate-readme@main
        with:
          gpt_token: ${{ secrets.GPT_API_TOKEN }}
          gpt_mode: 'gpt-4o-mini'
          target_languages: 'zh-hans,zh-hant,ja,pt-br'
